# Generated by Django 6.0.4 on 2026-04-28 10:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('index', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UPLOADING', 'Uploading'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('size', models.PositiveBigIntegerField()),
                ('content_type', models.CharField(default='application/octet-stream', max_length=128)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UPLOADING', 'Uploading'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ChunkExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_path', models.CharField(blank=True, max_length=500, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('chunk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='execution', to='storage_engine.chunk')),
            ],
        ),
        migrations.AddField(
            model_name='chunk',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='storage_engine.file'),
        ),
        migrations.AlterUniqueTogether(
            name='chunk',
            unique_together={('file', 'index')},
        ),
    ]
